version: "3.3"
services:
  rasa:
    build: "./"
    container_name: rasa-container
    network_mode: host

    volumes:
      - ./:/home/loan-bot
    ports:
      - "5005:5005"
      - "5055:5055"
      - "3000:3000"
    tty: true
networks:
  bot:
    driver: "bridge"
